import { Doctor, Hospital, Pharmacy, PatientProfile, Prescription, MedicalReportRecord, PatientCase } from '../types';

export const PAKISTAN_CITIES = [
  'All Cities',
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Peshawar',
  'Quetta',
  'Multan',
  'Faisalabad',
  'Hyderabad',
  'Sukkur',
  'Larkana',
  'Bahawalpur',
  'Swat',
  'Gujranwala',
  'Sialkot',
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Tariq Mahmood Khan',
    specialty: 'General Physician & Family Medicine',
    qualification: 'MBBS, FCPS (Internal Medicine)',
    pmdcNumber: 'PMDC-48291-P',
    hospital: 'Nishtar Hospital & Medical Complex',
    city: 'Multan',
    province: 'Punjab',
    address: 'Nishtar Road, Cantt, Multan',
    distance: '1.4 km',
    rating: 4.9,
    reviewsCount: 142,
    consultationFee: 1200,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    timing: '10:00 AM - 04:00 PM',
    languages: ['Urdu', 'Saraiki', 'Punjabi', 'English'],
    phone: '+92-300-7392811',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    experienceYears: 16,
  },
  {
    id: 'doc-2',
    name: 'Dr. Ayesha Siddiqa Baloch',
    specialty: 'Pediatrician & Child Specialist',
    qualification: 'MBBS, DCH, MCPS (Pediatrics)',
    pmdcNumber: 'PMDC-61920-B',
    hospital: 'Sandeman Provincial Hospital',
    city: 'Quetta',
    province: 'Balochistan',
    address: 'Circular Road, Quetta',
    distance: '2.1 km',
    rating: 4.8,
    reviewsCount: 98,
    consultationFee: 1000,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Sat'],
    timing: '09:30 AM - 02:00 PM',
    languages: ['Balochi', 'Pashto', 'Urdu', 'English'],
    phone: '+92-333-7819201',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1594824813581-2c676fef30e5?w=400&auto=format&fit=crop&q=80',
    experienceYears: 12,
  },
  {
    id: 'doc-3',
    name: 'Dr. Shahzad Ali Qureshi',
    specialty: 'Cardiologist (Heart Specialist)',
    qualification: 'MBBS, FCPS (Cardiology), MRCP (UK)',
    pmdcNumber: 'PMDC-31849-S',
    hospital: 'National Institute of Cardiovascular Diseases (NICVD)',
    city: 'Karachi',
    province: 'Sindh',
    address: 'Rafiqui Shaheed Road, Karachi',
    distance: '3.8 km',
    rating: 5.0,
    reviewsCount: 230,
    consultationFee: 2000,
    availableDays: ['Mon', 'Wed', 'Thu', 'Fri'],
    timing: '02:00 PM - 07:00 PM',
    languages: ['Sindhi', 'Urdu', 'English'],
    phone: '+92-321-9871234',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    experienceYears: 20,
  },
  {
    id: 'doc-4',
    name: 'Dr. Gulalai Khan Afridi',
    specialty: 'Pulmonologist & Chest Specialist',
    qualification: 'MBBS, FCPS (Pulmonology)',
    pmdcNumber: 'PMDC-55102-K',
    hospital: 'Lady Reading Hospital (LRH)',
    city: 'Peshawar',
    province: 'Khyber Pakhtunkhwa',
    address: 'Soekarno Square, Peshawar',
    distance: '2.6 km',
    rating: 4.7,
    reviewsCount: 114,
    consultationFee: 1500,
    availableDays: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat'],
    timing: '11:00 AM - 05:00 PM',
    languages: ['Pashto', 'Urdu', 'English'],
    phone: '+92-345-6677889',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    experienceYears: 14,
  },
  {
    id: 'doc-5',
    name: 'Dr. Usman Bashir Virk',
    specialty: 'Consultant Orthopedic Surgeon',
    qualification: 'MBBS, MS (Orthopedic Surgery)',
    pmdcNumber: 'PMDC-40112-L',
    hospital: 'Mayo Hospital & King Edward Medical University',
    city: 'Lahore',
    province: 'Punjab',
    address: 'Anarkali, Nila Gumbad, Lahore',
    distance: '4.2 km',
    rating: 4.9,
    reviewsCount: 175,
    consultationFee: 1800,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    timing: '03:00 PM - 08:00 PM',
    languages: ['Punjabi', 'Urdu', 'English'],
    phone: '+92-302-8819203',
    isOnlineAvailable: false,
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
    experienceYears: 18,
  },
  {
    id: 'doc-6',
    name: 'Dr. Zainab Noor Soomro',
    specialty: 'Gynecologist & Obstetrician',
    qualification: 'MBBS, FCPS (Obs & Gynae)',
    pmdcNumber: 'PMDC-59283-S',
    hospital: 'Civil Hospital Sukkur',
    city: 'Sukkur',
    province: 'Sindh',
    address: 'Minara Road, Sukkur',
    distance: '1.9 km',
    rating: 4.8,
    reviewsCount: 160,
    consultationFee: 1200,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timing: '10:00 AM - 03:00 PM',
    languages: ['Sindhi', 'Saraiki', 'Urdu', 'English'],
    phone: '+92-301-4433221',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    experienceYears: 11,
  },
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'Jinnah Postgraduate Medical Centre (JPMC)',
    type: 'Government Teaching Hospital',
    city: 'Karachi',
    province: 'Sindh',
    address: 'Rafiqui Shaheed Road, Cantt, Karachi',
    distance: '3.2 km',
    phone: '+92-21-99201300',
    ambulanceContact: '1122 / +92-21-99201300',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.6,
    photoUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-2',
    name: 'Mayo Hospital Emergency Trauma Centre',
    type: 'Government Teaching Hospital',
    city: 'Lahore',
    province: 'Punjab',
    address: 'Hospital Road, Anarkali, Lahore',
    distance: '2.5 km',
    phone: '+92-42-99211100',
    ambulanceContact: '1122',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.7,
    photoUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-3',
    name: 'Pakistan Institute of Medical Sciences (PIMS)',
    type: 'Government Teaching Hospital',
    city: 'Islamabad',
    province: 'Federal',
    address: 'G-8/3, Islamabad',
    distance: '4.0 km',
    phone: '+92-51-9261170',
    ambulanceContact: '1122 / 051-9261170',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.8,
    photoUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-4',
    name: 'Nishtar Hospital Multan',
    type: 'Government Teaching Hospital',
    city: 'Multan',
    province: 'Punjab',
    address: 'Nishtar Road, Multan',
    distance: '1.8 km',
    phone: '+92-61-9200231',
    ambulanceContact: '1122',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.5,
    photoUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-5',
    name: 'Lady Reading Hospital (LRH)',
    type: 'Government Teaching Hospital',
    city: 'Peshawar',
    province: 'Khyber Pakhtunkhwa',
    address: 'LRH Road, Peshawar',
    distance: '2.9 km',
    phone: '+92-91-9211430',
    ambulanceContact: '1122',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.6,
    photoUrl: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=500&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_PHARMACIES: Pharmacy[] = [
  {
    id: 'pharm-1',
    name: "Fazal Din's Pharma Plus",
    chain: "Fazal Din's",
    city: 'Lahore',
    province: 'Punjab',
    address: 'Mall Road & Jail Road Branches',
    distance: '1.2 km',
    phone: '+92-42-111-329-253',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '45 mins',
    commonMedsInStock: ['Panadol', 'Augmentin', 'Brufen', 'Ventolin Inhaler', 'ORS Nimkol', 'Risek', 'Insulin'],
    photoUrl: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'pharm-2',
    name: 'D. Watson Pharmacy & Superstore',
    chain: 'D. Watson',
    city: 'Islamabad',
    province: 'Federal',
    address: 'Blue Area & F-10 Markaz',
    distance: '2.0 km',
    phone: '+92-51-2824900',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '30-45 mins',
    commonMedsInStock: ['Panadol Syrup', 'Flagyl', 'Azomax', 'Loprin', 'Glucophage', 'Gaviscon', 'Cravit'],
    photoUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'pharm-3',
    name: 'Kausar Medicos 24/7',
    chain: 'Kausar',
    city: 'Karachi',
    province: 'Sindh',
    address: 'Clifton Block 2 & Saddar, Karachi',
    distance: '1.5 km',
    phone: '+92-21-35870000',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '40 mins',
    commonMedsInStock: ['Panadol CF', 'Ciprobay', 'Zyrtec', 'Disprin', 'Hydryllin', 'Novorapid Insulin'],
    photoUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'pharm-4',
    name: 'Servaid Pharmacy Express',
    chain: 'Servaid',
    city: 'Multan',
    province: 'Punjab',
    address: 'Bosan Road & Abdali Road, Multan',
    distance: '0.8 km',
    phone: '+92-61-111-737-824',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '30 mins',
    commonMedsInStock: ['Panadol', 'Amoxil', 'Arinac', 'Entamizole', 'Polyfax', 'Surbex Z', 'Gravinate'],
    photoUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_PROFILES: PatientProfile[] = [];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [];

export const INITIAL_REPORTS: MedicalReportRecord[] = [];

export const INITIAL_CASES: PatientCase[] = [];

