import { Doctor, Hospital, Pharmacy, PatientProfile, Prescription, MedicalReportRecord, PatientCase, VerificationLogRecord } from '../types';

export const PAKISTAN_CITIES = [
  'All Cities',
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Peshawar',
  'Quetta',
  'Multan',
  'Faisalabad',
  'Hyderabad',
  'Sukkur',
  'Larkana',
  'Bahawalpur',
  'Swat',
  'Gujranwala',
  'Sialkot',
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Tariq Mahmood Khan',
    specialty: 'General Physician & Family Medicine',
    qualification: 'MBBS, FCPS (Internal Medicine)',
    pmdcNumber: 'PMDC-48291-P',
    hospital: 'Nishtar Hospital & Medical Complex',
    city: 'Multan',
    province: 'Punjab',
    address: 'Nishtar Road, Cantt, Multan',
    distance: '1.4 km',
    rating: 4.9,
    reviewsCount: 142,
    consultationFee: 1200,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    timing: '10:00 AM - 04:00 PM',
    languages: ['Urdu', 'English'],
    phone: '+92-300-7392811',
    email: 'dr.tariq.khan@nishtar.edu.pk',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    experienceYears: 16,
    isVerified: true,
    verificationStatus: 'verified',
    pmdcCertificateUrl: 'PMDC_Certificate_Khan_48291P.pdf',
    degreeDocumentUrl: 'MBBS_FCPS_Khan_Degrees.pdf',
    verificationDocumentName: 'PMDC_Permanent_License_48291P.pdf',
    registeredAt: '12 Jan 2024',
    verifiedAt: '15 Jan 2024',
    verifiedBy: 'Medical Admin Board',
  },
  {
    id: 'doc-2',
    name: 'Dr. Ayesha Siddiqa Baloch',
    specialty: 'Pediatrician & Child Specialist',
    qualification: 'MBBS, DCH, MCPS (Pediatrics)',
    pmdcNumber: 'PMDC-61920-B',
    hospital: 'Sandeman Provincial Hospital',
    city: 'Quetta',
    province: 'Balochistan',
    address: 'Circular Road, Quetta',
    distance: '2.1 km',
    rating: 4.8,
    reviewsCount: 98,
    consultationFee: 1000,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Sat'],
    timing: '09:30 AM - 02:00 PM',
    languages: ['Urdu', 'English'],
    phone: '+92-333-7819201',
    email: 'dr.ayesha.baloch@sph.gob.pk',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=400&auto=format&fit=crop&q=80',
    experienceYears: 12,
    isVerified: true,
    verificationStatus: 'verified',
    pmdcCertificateUrl: 'PMDC_Certificate_Baloch_61920B.pdf',
    degreeDocumentUrl: 'MBBS_MCPS_Baloch.pdf',
    verificationDocumentName: 'PMDC_License_Baloch_61920B.pdf',
    registeredAt: '03 Feb 2024',
    verifiedAt: '05 Feb 2024',
    verifiedBy: 'Chief Medical Officer',
  },
  {
    id: 'doc-3',
    name: 'Dr. Shahzad Ali Qureshi',
    specialty: 'Cardiologist (Heart Specialist)',
    qualification: 'MBBS, FCPS (Cardiology), MRCP (UK)',
    pmdcNumber: 'PMDC-31849-S',
    hospital: 'National Institute of Cardiovascular Diseases (NICVD)',
    city: 'Karachi',
    province: 'Sindh',
    address: 'Rafiqui Shaheed Road, Karachi',
    distance: '3.8 km',
    rating: 5.0,
    reviewsCount: 230,
    consultationFee: 2000,
    availableDays: ['Mon', 'Wed', 'Thu', 'Fri'],
    timing: '02:00 PM - 07:00 PM',
    languages: ['Urdu', 'English'],
    phone: '+92-321-9871234',
    email: 'dr.shahzad.qureshi@nicvd.org.pk',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    experienceYears: 20,
    isVerified: true,
    verificationStatus: 'verified',
    pmdcCertificateUrl: 'PMDC_Cardiology_License_31849S.pdf',
    degreeDocumentUrl: 'MBBS_FCPS_MRCP_Qureshi.pdf',
    verificationDocumentName: 'PMDC_Permanent_License_31849S.pdf',
    registeredAt: '18 Nov 2023',
    verifiedAt: '20 Nov 2023',
    verifiedBy: 'Medical Admin Board',
  },
  {
    id: 'doc-4',
    name: 'Dr. Gulalai Khan Afridi',
    specialty: 'Pulmonologist & Chest Specialist',
    qualification: 'MBBS, FCPS (Pulmonology)',
    pmdcNumber: 'PMDC-55102-K',
    hospital: 'Lady Reading Hospital (LRH)',
    city: 'Peshawar',
    province: 'Khyber Pakhtunkhwa',
    address: 'Soekarno Square, Peshawar',
    distance: '2.6 km',
    rating: 4.7,
    reviewsCount: 114,
    consultationFee: 1500,
    availableDays: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat'],
    timing: '11:00 AM - 05:00 PM',
    languages: ['Urdu', 'English'],
    phone: '+92-345-6677889',
    email: 'dr.gulalai.afridi@lrh.edu.pk',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    experienceYears: 14,
    isVerified: true,
    verificationStatus: 'verified',
    pmdcCertificateUrl: 'PMDC_Certificate_Afridi_55102K.pdf',
    degreeDocumentUrl: 'FCPS_Pulmonology_Afridi.pdf',
    verificationDocumentName: 'PMDC_License_Afridi_55102K.pdf',
    registeredAt: '24 Jan 2024',
    verifiedAt: '26 Jan 2024',
    verifiedBy: 'Chief Medical Officer',
  },
  {
    id: 'doc-5',
    name: 'Dr. Usman Bashir Virk',
    specialty: 'Consultant Orthopedic Surgeon',
    qualification: 'MBBS, MS (Orthopedic Surgery)',
    pmdcNumber: 'PMDC-40112-L',
    hospital: 'Mayo Hospital & King Edward Medical University',
    city: 'Lahore',
    province: 'Punjab',
    address: 'Anarkali, Nila Gumbad, Lahore',
    distance: '4.2 km',
    rating: 4.9,
    reviewsCount: 175,
    consultationFee: 1800,
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    timing: '03:00 PM - 08:00 PM',
    languages: ['Urdu', 'English'],
    phone: '+92-302-8819203',
    email: 'dr.usman.virk@kemu.edu.pk',
    isOnlineAvailable: false,
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
    experienceYears: 18,
    isVerified: true,
    verificationStatus: 'verified',
    pmdcCertificateUrl: 'PMDC_Certificate_Virk_40112L.pdf',
    degreeDocumentUrl: 'MBBS_MS_Orthopedic_Virk.pdf',
    verificationDocumentName: 'PMDC_License_Virk_40112L.pdf',
    registeredAt: '10 Feb 2024',
    verifiedAt: '12 Feb 2024',
    verifiedBy: 'Medical Admin Board',
  },
  {
    id: 'doc-6',
    name: 'Dr. Zainab Noor Soomro',
    specialty: 'Gynecologist & Obstetrician',
    qualification: 'MBBS, FCPS (Obs & Gynae)',
    pmdcNumber: 'PMDC-59283-S',
    hospital: 'Civil Hospital Sukkur',
    city: 'Sukkur',
    province: 'Sindh',
    address: 'Minara Road, Sukkur',
    distance: '1.9 km',
    rating: 4.8,
    reviewsCount: 160,
    consultationFee: 1200,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timing: '10:00 AM - 03:00 PM',
    languages: ['Urdu', 'English'],
    phone: '+92-301-4433221',
    email: 'dr.zainab.soomro@chsukkur.gov.pk',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1594824813589-980e92759e69?w=400&auto=format&fit=crop&q=80',
    experienceYears: 11,
    isVerified: true,
    verificationStatus: 'verified',
    pmdcCertificateUrl: 'PMDC_Certificate_Soomro_59283S.pdf',
    degreeDocumentUrl: 'FCPS_ObsGynae_Soomro.pdf',
    verificationDocumentName: 'PMDC_License_Soomro_59283S.pdf',
    registeredAt: '15 Mar 2024',
    verifiedAt: '18 Mar 2024',
    verifiedBy: 'Chief Medical Officer',
  },
  // Pending verification applications for Admin Workflow inspection
  {
    id: 'doc-pending-1',
    name: 'Dr. Hamza Farooq',
    specialty: 'Dermatologist & Skin Specialist',
    qualification: 'MBBS, MCPS (Dermatology)',
    pmdcNumber: 'PMDC-74918-P',
    hospital: 'Pakistan Institute of Medical Sciences (PIMS)',
    city: 'Islamabad',
    province: 'Islamabad Capital Territory',
    address: 'Sector G-8/3, Islamabad',
    distance: '2.5 km',
    rating: 5.0,
    reviewsCount: 0,
    consultationFee: 1500,
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    timing: '11:00 AM - 04:00 PM',
    languages: ['Urdu', 'English'],
    phone: '+92-300-5544332',
    email: 'dr.hamza.farooq@pims.edu.pk',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&auto=format&fit=crop&q=80',
    experienceYears: 7,
    isVerified: false,
    verificationStatus: 'pending',
    pmdcCertificateUrl: 'PMDC_Certificate_Farooq_74918P.pdf',
    degreeDocumentUrl: 'MBBS_MCPS_Farooq_Degrees.pdf',
    verificationDocumentName: 'PMDC_Official_License_Certificate_Farooq.pdf',
    registeredAt: 'Just Now',
  },
  {
    id: 'doc-pending-2',
    name: 'Dr. Nadia Batool Qazi',
    specialty: 'Endocrinologist & Diabetes Specialist',
    qualification: 'MBBS, FCPS (Endocrinology)',
    pmdcNumber: 'PMDC-68214-L',
    hospital: 'Services Hospital Lahore',
    city: 'Lahore',
    province: 'Punjab',
    address: 'Ghaus-ul-Azam Road, Jail Road, Lahore',
    distance: '3.1 km',
    rating: 5.0,
    reviewsCount: 0,
    consultationFee: 2200,
    availableDays: ['Tue', 'Thu', 'Sat'],
    timing: '01:00 PM - 06:00 PM',
    languages: ['Urdu', 'English', 'Punjabi'],
    phone: '+92-321-4455667',
    email: 'dr.nadia.qazi@sims.edu.pk',
    isOnlineAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    experienceYears: 9,
    isVerified: false,
    verificationStatus: 'pending',
    pmdcCertificateUrl: 'PMDC_Certificate_Qazi_68214L.pdf',
    degreeDocumentUrl: 'FCPS_Endocrinology_Qazi.pdf',
    verificationDocumentName: 'PMDC_License_Certificate_Qazi_68214L.pdf',
    registeredAt: '1 Hour Ago',
  },
];

export const INITIAL_VERIFICATION_LOGS: VerificationLogRecord[] = [
  {
    id: 'log-1',
    doctorId: 'doc-1',
    doctorName: 'Dr. Tariq Mahmood Khan',
    pmdcNumber: 'PMDC-48291-P',
    specialty: 'General Physician & Family Medicine',
    qualification: 'MBBS, FCPS (Internal Medicine)',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    action: 'verified',
    timestamp: '15 Jan 2024, 10:45 AM',
    adminNote: 'PMDC permanent license #PMDC-48291-P verified via PMDC online portal. FCPS Medicine degree and Nishtar Hospital affiliation validated. Doctor approved for tele-triage consultations and digital prescriptions.',
    verifiedBy: 'Medical Admin Board (Chief Registrar)',
    documentName: 'PMDC_Permanent_License_48291P.pdf',
    hospital: 'Nishtar Hospital & Medical Complex',
    city: 'Multan',
  },
  {
    id: 'log-2',
    doctorId: 'doc-2',
    doctorName: 'Dr. Ayesha Siddiqa Baloch',
    pmdcNumber: 'PMDC-61920-B',
    specialty: 'Pediatrician & Child Specialist',
    qualification: 'MBBS, DCH, MCPS (Pediatrics)',
    avatarUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=400&auto=format&fit=crop&q=80',
    action: 'verified',
    timestamp: '05 Feb 2024, 02:15 PM',
    adminNote: 'License #PMDC-61920-B verified active and compliant. Pediatric credentials and Sandeman Provincial Hospital Quetta records cross-checked.',
    verifiedBy: 'Chief Medical Officer',
    documentName: 'PMDC_License_Baloch_61920B.pdf',
    hospital: 'Sandeman Provincial Hospital',
    city: 'Quetta',
  },
  {
    id: 'log-3',
    doctorId: 'doc-3',
    doctorName: 'Dr. Shahzad Ali Qureshi',
    pmdcNumber: 'PMDC-31849-S',
    specialty: 'Cardiologist (Heart Specialist)',
    qualification: 'MBBS, FCPS (Cardiology), MRCP (UK)',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    action: 'verified',
    timestamp: '20 Nov 2023, 11:30 AM',
    adminNote: 'NICVD Cardiology fellowship credentials verified. Clean disciplinary record confirmed with Pakistan Medical & Dental Council. Profile activated.',
    verifiedBy: 'Medical Admin Board',
    documentName: 'PMDC_Permanent_License_31849S.pdf',
    hospital: 'NICVD Karachi',
    city: 'Karachi',
  },
  {
    id: 'log-4',
    doctorId: 'doc-rej-1',
    doctorName: 'Dr. Kamran Munir',
    pmdcNumber: 'PMDC-19823-X',
    specialty: 'General Surgery',
    qualification: 'MBBS',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    action: 'rejected',
    timestamp: '18 Sep 2024, 04:30 PM',
    adminNote: 'Application rejected: Submitted PMDC registration number PMDC-19823-X is currently expired in the national registry. License document was not updated for the current calendar year. Applicant notified to submit valid renewal from PMDC Islamabad.',
    verifiedBy: 'Credentials Audit Committee',
    documentName: 'PMDC_Expired_License_Scan.pdf',
    hospital: 'Private Practice',
    city: 'Faisalabad',
  },
  {
    id: 'log-5',
    doctorId: 'doc-susp-1',
    doctorName: 'Dr. Babar Rizvi',
    pmdcNumber: 'PMDC-88219-L',
    specialty: 'Dermatologist',
    qualification: 'MBBS, Dip Derm',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
    action: 'suspended',
    timestamp: '22 Aug 2024, 03:10 PM',
    adminNote: 'License temporarily suspended pending regulatory inquiry regarding clinic operating hours and mandatory CPD credit compliance. Removed from all patient-facing search results.',
    verifiedBy: 'Chief Medical Officer',
    documentName: 'PMDC_Derm_License_Scan.pdf',
    hospital: 'City Skin Clinic',
    city: 'Lahore',
  },
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'Jinnah Postgraduate Medical Centre (JPMC)',
    type: 'Government Teaching Hospital',
    city: 'Karachi',
    province: 'Sindh',
    address: 'Rafiqui Shaheed Road, Cantt, Karachi',
    distance: '3.2 km',
    phone: '+92-21-99201300',
    ambulanceContact: '1122 / +92-21-99201300',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.6,
    photoUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-2',
    name: 'Mayo Hospital Emergency Trauma Centre',
    type: 'Government Teaching Hospital',
    city: 'Lahore',
    province: 'Punjab',
    address: 'Hospital Road, Anarkali, Lahore',
    distance: '2.5 km',
    phone: '+92-42-99211100',
    ambulanceContact: '1122',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.7,
    photoUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-3',
    name: 'Pakistan Institute of Medical Sciences (PIMS)',
    type: 'Government Teaching Hospital',
    city: 'Islamabad',
    province: 'Federal',
    address: 'G-8/3, Islamabad',
    distance: '4.0 km',
    phone: '+92-51-9261170',
    ambulanceContact: '1122 / 051-9261170',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.8,
    photoUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-4',
    name: 'Nishtar Hospital Multan',
    type: 'Government Teaching Hospital',
    city: 'Multan',
    province: 'Punjab',
    address: 'Nishtar Road, Multan',
    distance: '1.8 km',
    phone: '+92-61-9200231',
    ambulanceContact: '1122',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.5,
    photoUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'hosp-5',
    name: 'Lady Reading Hospital (LRH)',
    type: 'Government Teaching Hospital',
    city: 'Peshawar',
    province: 'Khyber Pakhtunkhwa',
    address: 'LRH Road, Peshawar',
    distance: '2.9 km',
    phone: '+92-91-9211430',
    ambulanceContact: '1122',
    hasEmergency24_7: true,
    hasIcu: true,
    rating: 4.6,
    photoUrl: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=500&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_PHARMACIES: Pharmacy[] = [
  {
    id: 'pharm-1',
    name: "Fazal Din's Pharma Plus",
    chain: "Fazal Din's",
    city: 'Lahore',
    province: 'Punjab',
    address: 'Mall Road & Jail Road Branches',
    distance: '1.2 km',
    phone: '+92-42-111-329-253',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '45 mins',
    commonMedsInStock: ['Panadol', 'Augmentin', 'Brufen', 'Ventolin Inhaler', 'ORS Nimkol', 'Risek', 'Insulin'],
    photoUrl: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'pharm-2',
    name: 'D. Watson Pharmacy & Superstore',
    chain: 'D. Watson',
    city: 'Islamabad',
    province: 'Federal',
    address: 'Blue Area & F-10 Markaz',
    distance: '2.0 km',
    phone: '+92-51-2824900',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '30-45 mins',
    commonMedsInStock: ['Panadol Syrup', 'Flagyl', 'Azomax', 'Loprin', 'Glucophage', 'Gaviscon', 'Cravit'],
    photoUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'pharm-3',
    name: 'Kausar Medicos 24/7',
    chain: 'Kausar',
    city: 'Karachi',
    province: 'Sindh',
    address: 'Clifton Block 2 & Saddar, Karachi',
    distance: '1.5 km',
    phone: '+92-21-35870000',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '40 mins',
    commonMedsInStock: ['Panadol CF', 'Ciprobay', 'Zyrtec', 'Disprin', 'Hydryllin', 'Novorapid Insulin'],
    photoUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'pharm-4',
    name: 'Servaid Pharmacy Express',
    chain: 'Servaid',
    city: 'Multan',
    province: 'Punjab',
    address: 'Bosan Road & Abdali Road, Multan',
    distance: '0.8 km',
    phone: '+92-61-111-737-824',
    isOpen24_7: true,
    hasDelivery: true,
    deliveryTime: '30 mins',
    commonMedsInStock: ['Panadol', 'Amoxil', 'Arinac', 'Entamizole', 'Polyfax', 'Surbex Z', 'Gravinate'],
    photoUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_PROFILES: PatientProfile[] = [];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [];

export const INITIAL_REPORTS: MedicalReportRecord[] = [];

export const INITIAL_CASES: PatientCase[] = [];

